apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-bootstrap
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: authentik-bootstrap
  data:
  - secretKey: secret-key
    remoteRef:
      key: secret/authentik/bootstrap
      property: secret-key
  - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
    remoteRef:
      key: secret/authentik/bootstrap
      property: bootstrap-password
  - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
    remoteRef:
      key: secret/authentik/bootstrap
      property: bootstrap-token
