teleport-cluster:
  clusterName: teleport.itruslan.ru

  annotations:
    service:
      metallb.universe.tf/address-pool: homelab
      external-dns.alpha.kubernetes.io/hostname: teleport.itruslan.ru

  initContainers:
    - name: envsubst-config
      image: alpine:3
      command:
        - sh
        - -c
        - |
          apk add --no-cache gettext >/dev/null 2>&1
          envsubst < /etc/teleport/teleport.yaml > /config-rendered/teleport.yaml
      env:
        - name: TELEPORT_POSTGRES_CONN
          valueFrom:
            secretKeyRef:
              name: teleport-pg-conn
              key: conn_string
      volumeMounts:
        - name: config
          mountPath: /etc/teleport
          readOnly: true
        - name: config-rendered
          mountPath: /config-rendered

  extraVolumes:
    - name: config-rendered
      emptyDir: {}

  extraVolumeMounts:
    - name: config-rendered
      mountPath: /config-rendered

  extraArgs:
    - --config=/config-rendered/teleport.yaml

  auth:
    extraEnv:
      - name: TELEPORT_POSTGRES_CONN
        valueFrom:
          secretKeyRef:
            name: teleport-pg-conn
            key: conn_string
    teleportConfig:
      teleport:
        storage:
          type: postgresql
          conn_string: "${TELEPORT_POSTGRES_CONN}"
      windows_desktop_service:
        enabled: yes
        listen_addr: "0.0.0.0:3028"
        public_addr: "teleport-wds.teleport.svc.cluster.local:3028"
        static_hosts:
          - name: windows-11
            addr: "192.168.99.100:3389"
            labels:
              env: homelab
  proxy:
    teleportConfig:
      version: v3
      teleport:
        auth_server: teleport-auth.teleport.svc.cluster.local:3025
        join_params:
          method: kubernetes
          token_name: teleport-proxy
      proxy_service:
        public_addr: teleport.itruslan.ru:443
        https_keypairs:
          - key_file: /etc/teleport-tls/tls.key
            cert_file: /etc/teleport-tls/tls.crt
