teleport-cluster:
  clusterName: teleport.itruslan.ru

  annotations:
    service:
      metallb.universe.tf/address-pool: homelab
      external-dns.alpha.kubernetes.io/hostname: teleport.itruslan.ru

  auth:
    extraEnv:
      - name: TELEPORT_POSTGRES_CONN
        valueFrom:
          secretKeyRef:
            name: teleport-pg-conn
            key: conn_string
    teleportConfig:
      teleport:
        storage:
          type: postgresql
          conn_string: "${TELEPORT_POSTGRES_CONN}"
      windows_desktop_service:
        enabled: yes
        listen_addr: "0.0.0.0:3028"
        public_addr: "teleport-wds.teleport.svc.cluster.local:3028"
        static_hosts:
          - name: windows-11
            addr: "192.168.99.100:3389"
            labels:
              env: homelab
      app_service:
        enabled: yes
        apps: []
