# Заполнить после: vault operator init -key-shares=1 -key-threshold=1
# kubectl -n vault create secret generic vault-unseal-keys \
#   --from-literal=key-1=<unseal_key>
apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault
type: Opaque
data: {}
