# TLS for Teleport Application Access: *.teleport.itruslan.ru (Yandex Certificate Manager).
# Issued via terraform homelab-infra terraform/yandex-cloud/yc-cm-teleport (cert id in remoteRef).
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: wildcard-teleport-apps-tls
spec:
  externalSecretName: wildcard-teleport-apps-tls
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - kube-public
            - kube-node-lease
            - cert-manager
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: yandex-certificate-manager
    refreshInterval: 1h
    target:
      name: wildcard-teleport-apps-tls
      template:
        type: kubernetes.io/tls
    data:
      - secretKey: tls.crt
        remoteRef:
          key: fpqmss9l19rkjkvh57bs
          property: chain
      - secretKey: tls.key
        remoteRef:
          key: fpqmss9l19rkjkvh57bs
          property: privateKey
