apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: wildcard-itruslan-ru-tls
spec:
  externalSecretName: wildcard-itruslan-ru-tls
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - kube-public
            - kube-node-lease
            - cert-manager
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: yandex-certificate-manager
    refreshInterval: 1h
    target:
      name: wildcard-itruslan-ru-tls
      template:
        type: kubernetes.io/tls
    data:
      - secretKey: tls.crt
        remoteRef:
          key: fpqrqkljugtjfthqqga8
          property: chain
      - secretKey: tls.key
        remoteRef:
          key: fpqrqkljugtjfthqqga8
          property: privateKey
