apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yc-sa-key
  namespace: cert-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: yc-sa-key
  data:
    - secretKey: key.json
      remoteRef:
        key: yandex-cloud/eso-sa-key
        property: value
