apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anylink-secret
  namespace: anylink
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: anylink-secret
  data:
    - secretKey: LINK_ADMIN_PASS
      remoteRef:
        key: homelab/anylink/anylink.itruslan.ru
        property: anylink_admin_pass
    - secretKey: LINK_JWT_SECRET
      remoteRef:
        key: homelab/anylink/anylink.itruslan.ru
        property: anylink_jwt_secret
