application:
  applicationName: vless

  deployment:
    strategy:
      type: Recreate

    image:
      repository: ghcr.io/mhsanaei/3x-ui
      tag: latest
      pullPolicy: Always

    env:
      X_UI_USER:
        valueFrom:
          secretKeyRef:
            name: vless-config
            key: username
      X_UI_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: vless-config
            key: password

    ports:
      - name: vless
        containerPort: 443
        hostPort: 443
        protocol: TCP
      - name: ui
        containerPort: 2053
        hostPort: 2053
        protocol: TCP

    volumes:
      vless-data:
        persistentVolumeClaim:
          claimName: xray-data

    volumeMounts:
      vless-data:
        mountPath: /etc/x-ui

    containerSecurityContext:
      runAsNonRoot: false
      readOnlyRootFilesystem: false

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 256Mi

  service:
    ports:
      - name: vless
        port: 443
        protocol: TCP
        targetPort: 443
      - name: ui
        port: 2053
        protocol: TCP
        targetPort: 2053

  persistence:
    enabled: false
