image:
  repository: ghcr.io/itruslan/rundeck-yc-scheduler
  tag: latest
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    memory: 2Gi

persistence:
  size: 5Gi
  storageClass: ""

service:
  port: 4440
  targetPort: 4440

rundeck:
  grailsUrl: ""
  serverAddress: "0.0.0.0"
  apiTokensDurationMax: "0"
  featureRepositoryEnabled: "false"
  database:
    secretName: rundeck-pg-credentials
    host: rundeck-pg-rw
    port: 5432
    name: rundeck
  oidc:
    enabled: false
    secretName: rundeck-oidc
    authentikDomain: ""
    appSlug: "rundeck"
    adminGroup: ""
    allowUnverifiedEmail: "false"
    proxy:
      image: "quay.io/oauth2-proxy/oauth2-proxy:v7.6.0"
      port: 4180
  acl:
    enabled: false
