image:
  repository: ghcr.io/itruslan/rundeck-yc-scheduler
  tag: latest
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    memory: 2Gi

persistence:
  size: 5Gi
  storageClass: ""

service:
  port: 4440

rundeck:
  grailsUrl: ""
  serverAddress: "0.0.0.0"
  apiTokensDurationMax: "0"
  featureRepositoryEnabled: "false"
  database:
    secretName: rundeck-pg-credentials
    host: rundeck-pg-rw
    port: 5432
    name: rundeck
