authentik:
  global:
    envFrom:
    - secretRef:
        name: authentik-bootstrap

  authentik:
    postgresql:
      host: authentik-pg-rw
      name: authentik
      user: authentik

  server:
    ingress:
      enabled: false

  postgresql:
    enabled: false

  redis:
    enabled: true
