application:
  applicationName: anylink

  deployment:
    image:
      repository: cherts/anylink
      tag: "0.13.1"

    containerSecurityContext:
      privileged: true
      readOnlyRootFilesystem: false
      runAsNonRoot: false

    args:
      - --conf=/app/conf/server.toml

    env:
      TZ:
        value: "Europe/Moscow"
      ANYLINK_IN_CONTAINER:
        value: "on"

    envFrom:
      anylink-secret:
        type: secret
        nameSuffix: secret

    ports:
      - name: admin
        containerPort: 8800
        protocol: TCP

    volumes:
      anylink-conf:
        configMap:
          name: anylink-conf
      anylink-ssl:
        secret:
          secretName: wildcard-itruslan-ru-tls
      anylink-db:
        persistentVolumeClaim:
          claimName: anylink-data

    volumeMounts:
      anylink-conf:
        mountPath: /app/conf/server.toml
        subPath: server.toml
      anylink-ssl:
        mountPath: /app/ssl
      anylink-db:
        mountPath: /app/db

  service:
    ports:
      - name: admin
        port: 8800
        protocol: TCP
        targetPort: 8800

  persistence:
    enabled: true
    mountPVC: false
    storageClass: proxmox-data
    accessMode: ReadWriteOnce
    size: 1Gi
