teleport-cluster:
  chartMode: ha
  proxyListenerMode: multiplex

  persistence:
    enabled: false

  authentication:
    type: github
    secondFactors: ["webauthn"]
    connector_name: github

  acme: false

  operator:
    enabled: true

  # TLS via existing wildcard cert (injected per cluster)
  tls:
    existingSecretName: wildcard-itruslan-ru-tls

  annotations:
    service:
      metallb.universe.tf/address-pool: homelab

  auth:
    teleportConfig:
      windows_desktop_service:
        enabled: yes
        listen_addr: "0.0.0.0:3028"
        static_hosts: []
