proxmox-csi-plugin:
  existingConfigSecret: proxmox-csi-config
  existingConfigSecretKey: config.yaml

  storageClass:
    - name: proxmox-nvme
      storage: local-lvm
      reclaimPolicy: Delete
      fstype: ext4
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    - name: proxmox-data
      storage: data
      reclaimPolicy: Delete
      fstype: ext4
      isDefault: false
