# Yandex CM: *.teleport.itruslan.ru (SNI для Application Access). cert id — из Terraform yc-cm-teleport (output cert_id).
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teleport-apps-tls-yc
  namespace: teleport
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: yandex-certificate-manager
  refreshInterval: 1h
  target:
    name: wildcard-teleport-apps-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      metadata:
        labels:
          app.kubernetes.io/name: teleport-cluster
          app.kubernetes.io/component: tls-wildcard-apps
  data:
    - secretKey: tls.crt
      remoteRef:
        key: fpqmss9l19rkjkvh57bs
        property: chain
    - secretKey: tls.key
      remoteRef:
        key: fpqmss9l19rkjkvh57bs
        property: privateKey
