apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teleport-github-oauth
  namespace: teleport
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: teleport-github-oauth
  data:
  - secretKey: client_secret
    remoteRef:
      key: homelab/teleport/github
      property: client_secret
