apiVersion: resources.teleport.dev/v2
kind: TeleportProvisionToken
metadata:
  name: teleport-app-agent
  namespace: teleport
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  join_method: kubernetes
  roles:
    - App
  kubernetes:
    allow:
      - service_account: teleport:teleport-app-agent
