apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: windows-access
  namespace: teleport
spec:
  allow:
    windows_desktop_labels:
      "*": ["*"]
    windows_desktop_logins:
      - itruslan
