apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fh-vps-anylink-secret
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: fh-vps-anylink-secret
  data:
  - secretKey: LINK_ADMIN_PASS
    remoteRef:
      key: homelab/anylink/fh-vps
      property: anylink_admin_pass
  - secretKey: LINK_JWT_SECRET
    remoteRef:
      key: homelab/anylink/fh-vps
      property: anylink_jwt_secret
