apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hshp-vps-gost-config
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: hshp-vps-gost-config
    creationPolicy: Owner
    template:
      data:
        gost.yml: |
          services:
          - name: http-proxy
            addr: ":8080"
            handler:
              type: http
              auther: auther-0
            listener:
              type: tcp
          - name: http-proxy-tls
            addr: ":8443"
            handler:
              type: http
              auther: auther-0
            listener:
              type: tls
              tls:
                certFile: /etc/gost/tls/tls.crt
                keyFile: /etc/gost/tls/tls.key
          - name: socks5-proxy
            addr: ":1080"
            handler:
              type: socks5
              auther: auther-0
            listener:
              type: tcp
          - name: socks5-proxy-tls
            addr: ":1443"
            handler:
              type: socks5
              auther: auther-0
            listener:
              type: tls
              tls:
                certFile: /etc/gost/tls/tls.crt
                keyFile: /etc/gost/tls/tls.key
          authers:
          - name: auther-0
            auths:
            - username: itruslan
              password: '{{ .itruslan_password }}'
            - username: petrov_ad
              password: '{{ .petrov_ad_password }}'
          log:
            output: stderr
            level: info
            format: json
  data:
  - secretKey: itruslan_password
    remoteRef:
      key: homelab/gost/hshp-vps-authers
      property: itruslan_password
  - secretKey: petrov_ad_password
    remoteRef:
      key: homelab/gost/hshp-vps-authers
      property: petrov_ad_password
