apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hshp-vps-k8s-creds
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: hshp-vps-k8s-creds
    template:
      data:
        token: '{{ "{{" }} .bearerToken {{ "}}" }}'
        ca: '{{ "{{" }} .caData | b64dec {{ "}}" }}'
  data:
  - secretKey: bearerToken
    remoteRef:
      key: homelab/clusters/hshp-vps
      property: bearerToken
  - secretKey: caData
    remoteRef:
      key: homelab/clusters/hshp-vps
      property: caData
