---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: hshp-vps-cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    kubernetes:
      remoteNamespace: cert-manager
      server:
        url: https://REDACTED:6443
        caProvider:
          type: Secret
          name: hshp-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: hshp-vps-k8s-creds
            namespace: external-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: hshp-vps-external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    kubernetes:
      remoteNamespace: external-dns
      server:
        url: https://REDACTED:6443
        caProvider:
          type: Secret
          name: hshp-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: hshp-vps-k8s-creds
            namespace: external-secrets
            key: token
