apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray
  namespace: vless
  labels:
    app.kubernetes.io/name: xray
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: xray
  template:
    metadata:
      labels:
        app: xray
    spec:
      containers:
      - name: xray
        image: ghcr.io/mhsanaei/3x-ui:latest
        imagePullPolicy: Always
        env:
        - name: X_UI_USER
          valueFrom:
            secretKeyRef:
              name: vless-config
              key: username
        - name: X_UI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vless-config
              key: password
        - name: X_UI_PORT
          value: "8443"
        ports:
        - name: vless
          containerPort: 443
          hostPort: 443
          protocol: TCP
        - name: ui
          containerPort: 8443
          hostPort: 8443
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /etc/x-ui
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: xray-data
