apiVersion: v1
kind: Service
metadata:
  name: xray
  namespace: vless
  labels:
    app.kubernetes.io/name: xray
spec:
  type: ClusterIP
  ports:
  - name: vless
    port: 443
    targetPort: 443
    protocol: TCP
  - name: ui
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: xray
