apiVersion: v1
kind: Service
metadata:
  name: xray
  namespace: vless
  labels:
    app.kubernetes.io/name: xray
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vless-yc.itruslan.ru
spec:
  type: LoadBalancer
  ports:
  - name: vless
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: xray
