apiVersion: v1
kind: Service
metadata:
  name: xray
  namespace: vless
  labels:
    app.kubernetes.io/name: xray
spec:
  type: NodePort
  ports:
  - name: vless
    port: 8443
    targetPort: 8443
    nodePort: 30443
    protocol: TCP
  selector:
    app: xray
