tls:
  enabled: true
  issuer: letsencrypt
  domains:
  - fh-vps.itruslan.ru

service:
  type: LoadBalancer
  ports:
  - name: http-proxy
    port: 8080
    protocol: TCP
  - name: http-proxy-tls
    port: 8443
    protocol: TCP
  - name: socks5-proxy
    port: 1080
    protocol: TCP
  - name: socks5-proxy-tls
    port: 1443
    protocol: TCP
