apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: openclaw
data:
  openclaw.json: |
    {
      "gateway": {
        "bind": "lan",
        "port": 18789,
        "controlUi": {
          "dangerouslyDisableDeviceAuth": true,
          "allowedOrigins": [
            "https://openclaw.itruslan.ru"
          ]
        }
      }
    }
