apiVersion: v1
kind: Service
metadata:
  name: gost
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.hostname }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gost
  ports:
  - name: http-proxy
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: TCP
  - name: socks5-proxy
    port: {{ .Values.service.socks5Port }}
    targetPort: {{ .Values.service.socks5Port }}
    protocol: TCP
