apiVersion: v1
kind: Service
metadata:
  name: gost
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gost
  ports:
  - name: http-proxy
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: TCP
  - name: socks5-proxy
    port: {{ .Values.service.socks5Port }}
    targetPort: {{ .Values.service.socks5Port }}
    protocol: TCP
