apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rundeck
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
