apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-api
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mikrotik-api
  data:
    - secretKey: url
      remoteRef:
        key: mikrotik/api
        property: url
    - secretKey: username
      remoteRef:
        key: mikrotik/api
        property: username
    - secretKey: password
      remoteRef:
        key: mikrotik/api
        property: password
