apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: yandex-certificate-manager
spec:
  provider:
    yandexcertificatemanager:
      auth:
        authorizedKeySecretRef:
          name: yc-sa-key
          namespace: cert-sync
          key: key.json
