apiVersion: apps/v1
kind: Deployment
metadata:
  name: gost
  namespace: gost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gost
  template:
    metadata:
      labels:
        app: gost
      annotations:
        reloader.stakater.com/auto: "true"
        secret.reloader.stakater.com/reload: "gost-config,wildcard-itruslan-ru-tls"
    spec:
      containers:
      - name: gost
        image: gogost/gost:latest
        imagePullPolicy: IfNotPresent
        args:
        - -C
        - /etc/gost/gost.yml
        volumeMounts:
        - name: config
          mountPath: /etc/gost
          readOnly: true
        - name: tls
          mountPath: /etc/gost/tls
          readOnly: true
        resources: {}
      volumes:
      - name: config
        secret:
          secretName: gost-config
      - name: tls
        secret:
          secretName: wildcard-itruslan-ru-tls
