apiVersion: v1
kind: Service
metadata:
  name: gost
  namespace: gost
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gost.itruslan.ru
spec:
  type: LoadBalancer
  selector:
    app: gost
  ports:
  - name: http-proxy
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: socks5-proxy
    port: 1080
    targetPort: 1080
    protocol: TCP
  - name: http-proxy-tls
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: socks5-proxy-tls
    port: 1443
    targetPort: 1443
    protocol: TCP
