apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rundeck-pg-credentials
  namespace: rundeck
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: rundeck-pg-credentials
  data:
  - secretKey: username
    remoteRef:
      key: rundeck/pg
      property: username
  - secretKey: password
    remoteRef:
      key: rundeck/pg
      property: password
