apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rundeck-oidc
  namespace: rundeck
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: rundeck-oidc
  data:
  - secretKey: clientId
    remoteRef:
      key: authentik/apps/rundeck
      property: clientId
  - secretKey: clientSecret
    remoteRef:
      key: authentik/apps/rundeck
      property: clientSecret
  - secretKey: cookieSecret
    remoteRef:
      key: authentik/apps/rundeck
      property: cookieSecret
