apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rundeck-pg
  namespace: rundeck
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instances: 1
  bootstrap:
    initdb:
      database: rundeck
      owner: rundeck
      secret:
        name: rundeck-pg-credentials
  storage:
    size: 5Gi
