{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anylink-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: anylink-tls
  issuerRef:
    name: {{ .Values.tls.issuer }}
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.tls.domain }}
  {{- range .Values.tls.extraDomains }}
  - {{ . }}
  {{- end }}
{{- end }}
