apiVersion: v1
kind: ConfigMap
metadata:
  name: anylink-conf
  namespace: anylink
data:
  server.toml: |
    db_type = "sqlite3"
    db_source = "/app/db/anylink.db"

    cert_file = "/app/ssl/tls.crt"
    cert_key = "/app/ssl/tls.key"

    files_path = "/app/conf/files"
    profile = "/app/conf/profile.xml"
    profile_name = "anylink"

    log_level = "info"
    http_server_log = "true"
    pprof = false

    issuer = "Cheburnet Industries"
    admin_user = "admin"
    admin_pass = "placeholder"
    admin_otp = ""
    jwt_secret = "placeholder"

    server_addr = ":8443"
    server_dtls = false
    server_dtls_addr = ":8443"
    admin_addr = ":8800"
    proxy_protocol = false

    link_mode = "tun"
    ipv4_master = "ens3"
    ipv4_cidr = "10.21.99.0/24"
    ipv4_gateway = "10.21.99.1"
    ipv4_start = "10.21.99.100"
    ipv4_end = "10.21.99.200"

    max_client = 20
    max_user_client = 3
    ip_lease = 86400
    default_group = "all"

    cstp_keepalive = 3
    cstp_dpd = 20
    mobile_keepalive = 4
    mobile_dpd = 60

    mtu = 1460
    default_domain = "fh-vps.itruslan.ru"

    idle_timeout = 0
    session_timeout = 3600
    audit_interval = -1

    show_sql = false
    iptables_nat = true
    compression = false
    no_compress_limit = 256
    display_error = true
    exclude_export_ip = true
