apiVersion: apps/v1
kind: Deployment
metadata:
  name: anylink
  namespace: anylink
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: anylink
  template:
    metadata:
      labels:
        app: anylink
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: anylink
        image: cherts/anylink:0.13.1
        imagePullPolicy: IfNotPresent
        args:
        - --conf=/app/conf/server.toml
        securityContext:
          privileged: true
          runAsNonRoot: false
          readOnlyRootFilesystem: false
        env:
        - name: TZ
          value: "Europe/Moscow"
        - name: ANYLINK_IN_CONTAINER
          value: "on"
        envFrom:
        - secretRef:
            name: anylink-secret
        volumeMounts:
        - name: config
          mountPath: /app/conf/server.toml
          subPath: server.toml
        - name: tls
          mountPath: /app/ssl
        - name: data
          mountPath: /app/db
        resources: {}
      volumes:
      - name: config
        configMap:
          name: anylink-conf
      - name: tls
        secret:
          secretName: anylink-tls
      - name: data
        persistentVolumeClaim:
          claimName: anylink-data
