apiVersion: apps/v1
kind: Deployment
metadata:
  name: anylink
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: anylink
  template:
    metadata:
      labels:
        app: anylink
      annotations:
        checksum/config: {{ .Values.config | toYaml | sha256sum }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: anylink
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --conf=/app/conf/server.toml
        securityContext:
          privileged: true
          runAsNonRoot: false
          readOnlyRootFilesystem: false
        env:
        - name: TZ
          value: "Europe/Moscow"
        - name: ANYLINK_IN_CONTAINER
          value: "on"
        envFrom:
        - secretRef:
            name: anylink-secret
        volumeMounts:
        - name: config
          mountPath: /app/conf/server.toml
          subPath: server.toml
        - name: tls
          mountPath: /app/ssl
        - name: data
          mountPath: /app/db
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: anylink-conf
      - name: tls
        secret:
          secretName: anylink-tls
      - name: data
        persistentVolumeClaim:
          claimName: anylink-data
