apiVersion: v1
kind: Service
metadata:
  name: anylink-vpn
  namespace: anylink
  annotations:
    external-dns.alpha.kubernetes.io/hostname: fh-vps.itruslan.ru,anylink.fh.itruslan.ru
spec:
  type: LoadBalancer
  selector:
    app: anylink
  ports:
  - name: vpn-tcp
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: vpn-udp
    port: 443
    targetPort: 8443
    protocol: UDP
  sessionAffinity: ClientIP
