apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-bootstrap
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: authentik-bootstrap
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: authentik/bootstrap
      property: secret-key
  - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
    remoteRef:
      key: authentik/bootstrap
      property: bootstrap-password
  - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
    remoteRef:
      key: authentik/bootstrap
      property: bootstrap-token
  - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
    remoteRef:
      key: authentik/bootstrap
      property: pg-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-pg-credentials
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: authentik-pg-credentials
  data:
  - secretKey: username
    remoteRef:
      key: authentik/bootstrap
      property: pg-username
  - secretKey: password
    remoteRef:
      key: authentik/bootstrap
      property: pg-password
