apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-pg-credentials
  storage:
    size: 5Gi
