apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: proxmox-lb
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 4096

    defaults
      log global
      mode tcp
      option tcplog
      option dontlognull
      timeout connect 5s
      timeout client 30s
      timeout server 30s

    frontend proxmox_front
      bind *:8006
      default_backend proxmox_back

    backend proxmox_back
      balance source
      option tcp-check
      server pve-1 192.168.99.241:8006 ssl verify none check
      server pve-2 192.168.99.242:8006 ssl verify none check
      server pve-3 192.168.99.243:8006 ssl verify none check

    frontend pve-1_front
      bind *:9000
      default_backend pve-1_back

    backend pve-1_back
      server pve-1 192.168.99.241:8006 ssl verify none

    frontend pve-2_front
      bind *:9001
      default_backend pve-2_back

    backend pve-2_back
      server pve-2 192.168.99.242:8006 ssl verify none

    frontend pve-3_front
      bind *:9002
      default_backend pve-3_back

    backend pve-3_back
      server pve-3 192.168.99.243:8006 ssl verify none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: proxmox-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:lts-alpine
          ports:
            - containerPort: 8006
            - containerPort: 9000
            - containerPort: 9001
            - containerPort: 9002
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: config
          configMap:
            name: haproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: proxmox-lb
spec:
  selector:
    app: haproxy
  ports:
    - name: https
      port: 8006
      targetPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: pve-1
  namespace: proxmox-lb
spec:
  selector:
    app: haproxy
  ipFamilyPolicy: SingleStack
  ipFamilies: ["IPv4"]
  ports:
    - name: https
      port: 8006
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: pve-2
  namespace: proxmox-lb
spec:
  selector:
    app: haproxy
  ipFamilyPolicy: SingleStack
  ipFamilies: ["IPv4"]
  ports:
    - name: https
      port: 8006
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: pve-3
  namespace: proxmox-lb
spec:
  selector:
    app: haproxy
  ipFamilyPolicy: SingleStack
  ipFamilies: ["IPv4"]
  ports:
    - name: https
      port: 8006
      targetPort: 9002
