---
# Push Cloudflare token to cert-manager namespace on fh-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: fh-vps-cloudflare-cert-manager
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: fh-vps-cert-manager
    kind: ClusterSecretStore
  selector:
    secret:
      name: fh-vps-cloudflare-token
  data:
  - match:
      secretKey: token
      remoteRef:
        remoteKey: cloudflare-token
        property: token
---
# Push Cloudflare token to external-dns namespace on fh-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: fh-vps-cloudflare-external-dns
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: fh-vps-external-dns
    kind: ClusterSecretStore
  selector:
    secret:
      name: fh-vps-cloudflare-token
  data:
  - match:
      secretKey: token
      remoteRef:
        remoteKey: cloudflare-token
        property: token
---
# Push rendered gost config to gost namespace on fh-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: fh-vps-gost-config
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: fh-vps-gost
    kind: ClusterSecretStore
  selector:
    secret:
      name: fh-vps-gost-config
  data:
  - match:
      secretKey: gost.yml
      remoteRef:
        remoteKey: gost-config
        property: gost.yml
---
# Push anylink secrets to anylink namespace on fh-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: fh-vps-anylink-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: fh-vps-anylink
    kind: ClusterSecretStore
  selector:
    secret:
      name: fh-vps-anylink-secret
  data:
  - match:
      secretKey: LINK_ADMIN_PASS
      remoteRef:
        remoteKey: anylink-secret
        property: LINK_ADMIN_PASS
  - match:
      secretKey: LINK_JWT_SECRET
      remoteRef:
        remoteKey: anylink-secret
        property: LINK_JWT_SECRET
