---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fh-vps-cert-manager
spec:
  provider:
    kubernetes:
      remoteNamespace: cert-manager
      server:
        url: {{ .Values.clusters.fhVps.serverUrl }}
        caProvider:
          type: Secret
          name: fh-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: fh-vps-k8s-creds
            namespace: external-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fh-vps-external-dns
spec:
  provider:
    kubernetes:
      remoteNamespace: external-dns
      server:
        url: {{ .Values.clusters.fhVps.serverUrl }}
        caProvider:
          type: Secret
          name: fh-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: fh-vps-k8s-creds
            namespace: external-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fh-vps-gost
spec:
  provider:
    kubernetes:
      remoteNamespace: gost
      server:
        url: {{ .Values.clusters.fhVps.serverUrl }}
        caProvider:
          type: Secret
          name: fh-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: fh-vps-k8s-creds
            namespace: external-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fh-vps-anylink
spec:
  provider:
    kubernetes:
      remoteNamespace: anylink
      server:
        url: {{ .Values.clusters.fhVps.serverUrl }}
        caProvider:
          type: Secret
          name: fh-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: fh-vps-k8s-creds
            namespace: external-secrets
            key: token
