---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fh-vps2-cert-manager
spec:
  provider:
    kubernetes:
      remoteNamespace: cert-manager
      server:
        url: https://fh-vps2.itruslan.ru:6443
        caProvider:
          type: Secret
          name: fh-vps2-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: fh-vps2-k8s-creds
            namespace: external-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fh-vps2-external-dns
spec:
  provider:
    kubernetes:
      remoteNamespace: external-dns
      server:
        url: https://fh-vps2.itruslan.ru:6443
        caProvider:
          type: Secret
          name: fh-vps2-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: fh-vps2-k8s-creds
            namespace: external-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fh-vps2-vless
spec:
  provider:
    kubernetes:
      remoteNamespace: vless
      server:
        url: https://fh-vps2.itruslan.ru:6443
        caProvider:
          type: Secret
          name: fh-vps2-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: fh-vps2-k8s-creds
            namespace: external-secrets
            key: token
