---
# Push Cloudflare token to cert-manager namespace on fh-vps2
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: fh-vps2-cloudflare-cert-manager
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: fh-vps2-cert-manager
    kind: ClusterSecretStore
  selector:
    secret:
      name: fh-vps2-cloudflare-token
  data:
  - conversionStrategy: None
    match:
      secretKey: token
      remoteRef:
        remoteKey: cloudflare-token
        property: token
---
# Push Cloudflare token to external-dns namespace on fh-vps2
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: fh-vps2-cloudflare-external-dns
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: fh-vps2-external-dns
    kind: ClusterSecretStore
  selector:
    secret:
      name: fh-vps2-cloudflare-token
  data:
  - conversionStrategy: None
    match:
      secretKey: token
      remoteRef:
        remoteKey: cloudflare-token
        property: token
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: fh-vps2-vless-config
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: fh-vps2-vless
    kind: ClusterSecretStore
  selector:
    secret:
      name: fh-vps2-vless-config
  data:
  - conversionStrategy: None
    match:
      secretKey: config.json
      remoteRef:
        remoteKey: vless-config
        property: config.json
  - conversionStrategy: None
    match:
      secretKey: username
      remoteRef:
        remoteKey: vless-config
        property: username
  - conversionStrategy: None
    match:
      secretKey: password
      remoteRef:
        remoteKey: vless-config
        property: password
