apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fh-vps2-vless-config
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: fh-vps2-vless-config
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: homelab/vless/fh-vps2
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: password
    remoteRef:
      key: homelab/vless/fh-vps2
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
