---
# Push Cloudflare token to cert-manager namespace on hshp-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: hshp-vps-cloudflare-cert-manager
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: hshp-vps-cert-manager
    kind: ClusterSecretStore
  selector:
    secret:
      name: hshp-vps-cloudflare-token
  data:
  - match:
      secretKey: token
      remoteRef:
        remoteKey: cloudflare-token
        property: token
---
# Push Cloudflare token to external-dns namespace on hshp-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: hshp-vps-cloudflare-external-dns
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: hshp-vps-external-dns
    kind: ClusterSecretStore
  selector:
    secret:
      name: hshp-vps-cloudflare-token
  data:
  - match:
      secretKey: token
      remoteRef:
        remoteKey: cloudflare-token
        property: token
---
# Push rendered gost config to gost namespace on hshp-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: hshp-vps-gost-config
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: hshp-vps-gost
    kind: ClusterSecretStore
  selector:
    secret:
      name: hshp-vps-gost-config
  data:
  - match:
      secretKey: gost.yml
      remoteRef:
        remoteKey: gost-config
        property: gost.yml
