apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yc-vps-vless-config
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: yc-vps-vless-config
    creationPolicy: Owner
  data:
  - secretKey: config.json
    remoteRef:
      key: homelab/vless/yc-vps
      property: configJson
