---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: yc-vps-cert-manager
spec:
  provider:
    kubernetes:
      remoteNamespace: cert-manager
      server:
        url: https://yc-vps.itruslan.ru:6443
        caProvider:
          type: Secret
          name: yc-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: yc-vps-k8s-creds
            namespace: external-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: yc-vps-external-dns
spec:
  provider:
    kubernetes:
      remoteNamespace: external-dns
      server:
        url: https://yc-vps.itruslan.ru:6443
        caProvider:
          type: Secret
          name: yc-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: yc-vps-k8s-creds
            namespace: external-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: yc-vps-vless
spec:
  provider:
    kubernetes:
      remoteNamespace: vless
      server:
        url: https://yc-vps.itruslan.ru:6443
        caProvider:
          type: Secret
          name: yc-vps-k8s-creds
          namespace: external-secrets
          key: ca
      auth:
        token:
          bearerToken:
            name: yc-vps-k8s-creds
            namespace: external-secrets
            key: token

