---
# Push Cloudflare token to cert-manager namespace on yc-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: yc-vps-cloudflare-cert-manager
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: yc-vps-cert-manager
    kind: ClusterSecretStore
  selector:
    secret:
      name: yc-vps-cloudflare-token
  data:
  - conversionStrategy: None
    match:
      secretKey: token
      remoteRef:
        remoteKey: cloudflare-token
        property: token
---
# Push Cloudflare token to external-dns namespace on yc-vps
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: yc-vps-cloudflare-external-dns
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: yc-vps-external-dns
    kind: ClusterSecretStore
  selector:
    secret:
      name: yc-vps-cloudflare-token
  data:
  - conversionStrategy: None
    match:
      secretKey: token
      remoteRef:
        remoteKey: cloudflare-token
        property: token
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: yc-vps-vless-config
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: yc-vps-vless
    kind: ClusterSecretStore
  selector:
    secret:
      name: yc-vps-vless-config
  data:
  - conversionStrategy: None
    match:
      secretKey: config.json
      remoteRef:
        remoteKey: vless-config
        property: config.json

