external-dns:
  provider:
    name: cloudflare
  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-token
        key: token
  domainFilters:
  - itruslan.ru
  policy: sync
  txtOwnerId: yc-vps
  sources:
  - ingress
  - service
