apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-yc-vps
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: cluster-yc-vps
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          deploy_cert_manager: "true"
          deploy_external_dns: "true"
          deploy_vless: "true"
      data:
        name: yc-vps
        server: '{{ .serverUrl }}'
        config: |
          {
            "bearerToken": "{{ .bearerToken }}",
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ .caData }}"
            }
          }
  data:
  - secretKey: bearerToken
    remoteRef:
      key: homelab/clusters/yc-vps
      property: bearerToken
  - secretKey: caData
    remoteRef:
      key: homelab/clusters/yc-vps
      property: caData
  - secretKey: serverUrl
    remoteRef:
      key: homelab/clusters/yc-vps
      property: serverUrl

