apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-fh-vps
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: cluster-fh-vps
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          deploy_gost: "true"
          deploy_cert_manager: "true"
          deploy_external_dns: "true"
          deploy_anylink: "true"
          deploy_alloy: "true"
          deploy_blackbox: "true"
      data:
        name: fh-vps
        server: '{{ "{{" }} .serverUrl {{ "}}" }}'
        config: |
          {
            "bearerToken": "{{ "{{" }} .bearerToken {{ "}}" }}",
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ "{{" }} .caData {{ "}}" }}"
            }
          }
  data:
  - secretKey: bearerToken
    remoteRef:
      key: homelab/clusters/fh-vps
      property: bearerToken
  - secretKey: caData
    remoteRef:
      key: homelab/clusters/fh-vps
      property: caData
  - secretKey: serverUrl
    remoteRef:
      key: homelab/clusters/fh-vps
      property: serverUrl
