apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-teleport
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: teleport
  url: https://charts.releases.teleport.dev
