apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    deploy_alloy: "true"
    deploy_anylink: "true"
    deploy_argocd: "true"
    deploy_authentik: "true"
    deploy_blackbox: "true"
    deploy_cert_sync: "true"
    deploy_cilium: "true"
    deploy_cnpg: "true"
    deploy_coredns: "true"
    deploy_external_dns: "true"
    deploy_external_secrets: "true"
    deploy_gateway: "true"
    deploy_gost: "true"
    deploy_grafana: "true"
    deploy_loki: "true"
    deploy_metallb: "true"
    deploy_proxmox_csi: "true"
    deploy_proxmox_lb: "true"
    deploy_reloader: "true"
    deploy_vault: "true"
    deploy_victoriametrics: "true"
stringData:
  name: homelab
  server: https://kubernetes.default.svc
  config: '{"tlsClientConfig":{"insecure":false}}'
