external-dns:
  provider:
    name: webhook
    webhook:
      image:
        repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
        tag: latest
      env:
        - name: MIKROTIK_BASEURL
          valueFrom:
            secretKeyRef:
              name: mikrotik-api
              key: url
        - name: MIKROTIK_USERNAME
          valueFrom:
            secretKeyRef:
              name: mikrotik-api
              key: username
        - name: MIKROTIK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mikrotik-api
              key: password
        - name: MIKROTIK_DEFAULT_COMMENT
          value: "Managed by ExternalDNS"
  sources:
    - gateway-httproute
    - service
  policy: sync
  txtOwnerId: homelab
