apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meshcommander-data
  namespace: meshcommander
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: proxmox-data
  resources:
    requests:
      storage: 1Gi
