image:
  repository: gogost/gost
  tag: "3"
  pullPolicy: IfNotPresent

upstreams:
  hshpVps:
    httpAddr: "hshp-vps.itruslan.ru:8443"
    socks5Addr: "hshp-vps.itruslan.ru:1443"
  gostFh:
    httpAddr: "REDACTED:8080"
    socks5Addr: "REDACTED:1080"

vault:
  secretPath: homelab/gost/users/itruslan

service:
  type: LoadBalancer
  hostname: gost.itruslan.ru
  httpPort: 8080
  socks5Port: 1080

resources: {}
