apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 1h
  target:
    name: argocd-oidc-secret
  data:
  - secretKey: clientSecret
    remoteRef:
      key: authentik/apps/argocd
      property: clientSecret
