image:
  repository: gogost/gost
  tag: "3"
  pullPolicy: IfNotPresent

vault:
  secretPath: homelab/gost/users/itruslan
  upstreamsPath: homelab/gost/upstreams

tls:
  certSecret: wildcard-itruslan-ru-tls

service:
  type: LoadBalancer
  hostname: gost.itruslan.ru
  httpPort: 8080
  httpTlsPort: 8443
  socks5Port: 1080
  socks5TlsPort: 1443

resources: {}
